//! A tabela de tradução: ajustes (ver `idioma.rs`). `(português, inglês)`, com os `{}` nas mesmas
//! posições de ordem; o português é o texto que está no código.

pub const TEXTOS: &[(&str, &str)] = &[
    // regras_dos_controles.rs: o título, os botões e as frases do §3.5 e do §4.3
    ("Ajustes da câmera", "Camera settings"),
    ("Restaurar automático", "Reset to auto"),
    ("Usar meus ajustes", "Use my settings"),
    ("Passar para Manual", "Switch to Manual"),
    ("Destrave a exposição para compensar.", "Unlock exposure to compensate."),
    ("Esta câmera tem foco fixo.", "This camera has fixed focus."),
    ("Outro app está controlando esta câmera. Feche-o para ajustar.", "Another app is controlling this camera. Close it to adjust."),
    ("Passe a exposição para Manual para escolher ganho e obturador.", "Set exposure to Manual to choose gain and shutter."),
    ("Esta câmera não oferece {}.", "This camera doesn't support {}."),
    ("A câmera usou {} em vez de {}.", "The camera used {} instead of {}."),
    ("Ganho {}", "Gain {}"),
    // regras_dos_controles.rs: o `{controle}` das frases (Propriedade::nome)
    ("o obturador", "shutter"),
    ("o ganho", "gain"),
    ("o brilho", "brightness"),
    ("o Kelvin", "Kelvin"),
    ("o foco manual", "manual focus"),
    ("a anti-cintilação", "anti-flicker"),
    // regras_dos_controles.rs: as abas e as opções
    ("Exposição", "Exposure"),
    ("Ganho e obturador", "Gain & shutter"),
    ("Balanço", "White balance"),
    ("Foco", "Focus"),
    ("Auto", "Auto"),
    ("Manual", "Manual"),
    ("Desligada", "Off"),
    ("Incandescente", "Incandescent"),
    ("Fluorescente", "Fluorescent"),
    ("Luz do dia", "Daylight"),
    ("Nublado", "Cloudy"),
    ("Kelvin", "Kelvin"),
    ("Travado", "Locked"),
    // modelo_dos_ajustes.rs: os rótulos, as notas e os nomes para o Narrador
    ("Lendo a câmera…", "Reading the camera…"),
    ("Brilho", "Brightness"),
    ("Ganho", "Gain"),
    ("Obturador", "Shutter"),
    ("Anti-cintilação", "Anti-flicker"),
    ("Travar exposição", "Lock exposure"),
    ("Travar balanço", "Lock white balance"),
    ("Perto ↔ Longe", "Near ↔ Far"),
    ("a trava de exposição", "exposure lock"),
    ("o ganho e o obturador", "gain and shutter"),
    ("os presets de balanço", "white balance presets"),
    ("a trava de balanço", "white balance lock"),
    ("aba", "tab"),
    // R9b, o controle remoto da câmera (`docs/controle-remoto-da-camera.md`): quem filma
    ("Permitir controle remoto da câmera", "Allow remote camera control"),
    ("Controlado por {}", "Controlled by {}"),
    // regras_dos_controles.rs: pouca luz (§3.1), as frases do Android e do iOS com "nos ajustes da
    // câmera" no lugar da engrenagem
    ("Pouca luz: {} fps para clarear a imagem. Para {} fps, use a exposição manual nos ajustes da câmera.", "Low light: {} fps to brighten the picture. For {} fps, use manual exposure in Camera settings."),
    ("Pouca luz: {} fps para clarear a imagem. Mais luz no ambiente devolve os {} fps.", "Low light: {} fps to brighten the picture. More light in the room brings back {} fps."),
    ("Pouca luz: {} fps para clarear a imagem.", "Low light: {} fps to brighten the picture."),
    ("Pouca luz: {} fps", "Low light: {} fps"),
    // R9b: quem recebe (`modelo_dos_ajustes_remotos.rs`)
    ("Ajustes da câmera — {}", "Camera settings — {}"),
    ("O aparelho não permite controle remoto da câmera", "This device doesn't allow remote camera control"),
    ("Este aparelho não aceitou {}.", "This device didn't accept {}."),
    ("O aparelho não conseguiu aplicar o ajuste.", "The device couldn't apply the setting."),
    ("O aparelho não respondeu.", "The device didn't respond."),
    ("O aparelho não está mostrando uma câmera.", "The device isn't showing a camera."),
    ("O fabricante deste aparelho não libera {} para outros apps.", "This device's manufacturer doesn't allow {} for other apps."),
    ("O macOS não oferece {} para câmeras.", "macOS doesn't offer {} for cameras."),
    ("O iOS ajusta a cintilação sozinho.", "iOS handles flicker on its own."),
    ("Esta câmera não publica a calibração de cor que o Kelvin precisa.", "This camera doesn't publish the color calibration Kelvin needs."),
    ("Este aparelho não oferece {}.", "This device doesn't support {}."),
    ("ISO e obturador", "ISO & shutter"),
    ("Passe a exposição para Manual para escolher ISO e obturador.", "Set exposure to Manual to choose ISO and shutter."),
    ("ISO {}", "ISO {}"),
    ("ISO", "ISO"),
    ("ISO e o obturador", "ISO and shutter"),
    ("a compensação de exposição", "exposure compensation"),
    ("a exposição manual", "manual exposure"),
    ("o toque para focar", "tap to focus"),
    ("o ajuste", "the setting"),
];
