//! A tabela de tradução: janela (ver `idioma.rs`). `(português, inglês)`, com os `{}` nas mesmas
//! posições de ordem; o português é o texto que está no código.
//!
//! A janela principal, os textos da tabela de sessões que chegam a ela (`sessoes.rs`), e as regras
//! da tela estendida. Onde o português coincide com o do iOS, o inglês é o mesmo de lá
//! (`apps/ios/Quall/*/en.lproj`).

pub const TEXTOS: &[(&str, &str)] = &[
    ("Estender", "Extend"),
    ("Estender a área de trabalho", "Extend your desktop"),
    ("Crie um monitor novo para cada aparelho conectado. No outro aparelho, escolha Exibir.", "Create a new display for each connected device. On the other device, choose Receive."),
    // modelo_da_janela.rs — a barra e os painéis
    ("Espelhar", "Mirror"),
    ("Exibir", "Receive"),
    ("Teleprompter", "Teleprompter"),
    ("Ajustes", "Settings"),
    ("Este computador aparece como", "This computer appears as"),
    ("O que vamos espelhar?", "What should we mirror?"),
    ("Uma tela existente ou uma câmera. Quem exibe escolhe este computador na lista.", "An existing screen or a camera. The receiving device picks this computer from the list."),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("Uma tela, a tela estendida ou uma câmera. Quem exibe escolhe este computador na lista.", "A screen, the extended display or a camera. The receiving device picks this computer from the list."),
    ("Nenhum monitor foi encontrado.", "No display was found."),
    ("Na rede · ", "On the network · "),
    ("Sem rede", "No network"),
    ("Assistir outro aparelho", "Watch another device"),
    ("Escolha quem está espelhando. Na primeira vez, digite o PIN que aparece lá.", "Pick who is mirroring. The first time, type the PIN shown there."),
    ("Na rede agora", "On the network now"),
    ("procurando", "searching"),
    ("Ou digite o endereço", "Or type the address"),
    ("Deixe o PIN vazio se os dois já parearam.", "Leave the PIN empty if already paired."),
    ("Mostrar o texto", "Show the text"),
    ("Este computador vira o prompter e espera o controle.", "This computer becomes the prompter and waits for the remote."),
    ("Controlar", "Remote"),
    ("Comanda o texto que outro aparelho está mostrando.", "Drives the text another device is showing."),
    ("Texto com a câmera", "Text with camera"),
    ("O roteiro do lado da webcam. Só a câmera vai para a rede.", "The script beside the webcam. Only the camera is sent."),
    ("Um computador mostra o texto atrás do vidro; outro aparelho controla. O roteiro se edita dos dois lados.", "One computer shows the text behind the glass; another device drives it. The script can be edited on both sides."),
    ("Janela própria; tela cheia pelo botão da barra ou F11 (Esc sai); H esconde as faixas.", "Its own window; full screen from the toolbar button or F11 (Esc exits); H hides the bars."),
    ("Aparelhos pareados", "Paired devices"),
    ("Clique de novo para esquecer todos.", "Click again to forget them all."),
    ("Os aparelhos pareados entram sem PIN.", "Paired devices join without a PIN."),
    ("Nenhum aparelho pareado.", "No paired devices."),
    ("Diário", "Log"),
    ("Versão", "Version"),
    ("Licenças", "Licenses"),
    ("Privacidade", "Privacy"),
    ("Suporte", "Support"),
    ("Abrir as licenças de terceiros", "Open third-party licenses"),
    ("Abrir a política de privacidade", "Open the privacy policy"),
    ("Abrir a página de suporte", "Open the support page"),
    ("As licenças de terceiros não puderam ser abertas. Reinstale o Quall Monitor para recuperar o arquivo de avisos.", "The third-party licenses could not be opened. Reinstall Quall Monitor to restore the notices file."),
    ("A página não pôde ser aberta no navegador. Tente novamente ou escreva para suporte@queven.com.br.", "The page could not be opened in your browser. Try again or contact suporte@queven.com.br."),
    // modelo_da_janela.rs — a espera, o no ar, os vários, a conexão, o exibindo
    ("Encerrando…", "Ending…"),
    ("Aguardando", "Waiting"),
    ("Pronto para espelhar", "Ready to mirror"),
    ("No outro aparelho, abra o Quall em ", "On the other device, open Quall in "),
    (" e escolha ", " and pick "),
    (" na lista, ou digite o endereço abaixo.", " from the list, or type the address below."),
    (" e digite o endereço abaixo.", " and type the address below."),
    (" Vai a câmera ", " Sending the camera "),
    (" Vai ", " Sending "),
    (", com o som deste computador.", ", with this computer's audio."),
    (", sem som.", ", no audio."),
    ("Na primeira vez, o PIN", "The first time, the PIN"),
    ("ou pelo endereço", "or by address"),
    ("Aparelhos pareados entram direto.", "Paired devices connect right away."),
    ("Aparelho novo? PIN ", "New device? PIN "),
    ("Anunciando na rede — este nome aparece na lista dos outros aparelhos.", "Visible on the network — this name shows in other devices' lists."),
    ("Sem anúncio na rede: use o endereço acima.", "Not announcing on the network: use the address above."),
    ("No ar", "Live"),
    ("Espelhando para", "Mirroring to"),
    ("o outro aparelho", "the other device"),
    ("Origem", "Source"),
    ("Imagem", "Picture"),
    ("Rede", "Network"),
    ("Som", "Audio"),
    ("Parar encerra a sessão nos dois lados.", "Stop ends the session on both sides."),
    ("Espelhando para 1 aparelho", "Mirroring to 1 device"),
    ("Espelhando para {} aparelhos", "Mirroring to {} devices"),
    ("Mais um aparelho", "One more device"),
    ("Conectando", "Connecting"),
    ("O outro aparelho precisa já ter clicado em Espelhar: quem exibe só entra depois de quem transmite estar esperando.", "The other device must have already clicked Mirror: the receiver can only join once the sender is waiting."),
    ("Conectado", "Connected"),
    ("do outro aparelho", "from the other device"),
    ("de {}", "from {}"),
    ("O vídeo está na outra janela.", "The video is in the other window."),
    ("Fechando o teleprompter aberto para abrir no papel pedido…", "Closing the open teleprompter to reopen it in the chosen role…"),
    ("O teleprompter aberto não fechou em 45 s. Feche a janela dele e clique no cartão de novo.", "The open teleprompter didn't close within 45 s. Close its window and click the card again."),
    // modelo_da_janela.rs — os controles e os nomes para o Narrador
    ("Mandar o som deste computador", "Send this computer's audio"),
    ("Vai o que o Windows estiver tocando.", "Whatever Windows is playing goes along."),
    ("Microfone", "Microphone"),
    ("Começa desligado. O som da câmera é o do microfone.", "Starts off. The camera's audio is the microphone."),
    ("Esquecer de verdade", "Really forget"),
    ("Esquecer pareamentos", "Forget pairings"),
    ("Abrir a pasta", "Open folder"),
    ("Cancelar", "Cancel"),
    ("Parar", "Stop"),
    ("Mudo", "Mute"),
    ("Tocar o som mesmo com a câmera do Quall em uso", "Play audio even with the Quall camera in use"),
    ("Numa chamada com a câmera virtual, o som continua tocando aqui.", "In a call with the virtual camera, audio keeps playing here."),
    ("Detalhes", "Details"),
    ("Microfone, {}", "Microphone, {}"),
    ("Endereço do outro aparelho", "Other device's address"),
    ("PIN do outro aparelho; vazio se os dois já parearam", "Other device's PIN; empty if already paired"),
    ("Esquecer de verdade: os aparelhos vão pedir o PIN outra vez", "Really forget: devices will ask for the PIN again"),
    ("Abrir a pasta do diário", "Open the log folder"),
    ("Copiado: {}", "Copied: {}"),
    ("Copiar o endereço {}", "Copy the address {}"),
    ("Volume {}", "Volume {}"),
    // modelo_da_janela.rs — as legendas dos redondos da câmera
    ("Sem acesso", "No access"),
    ("Mic desligado", "Mic off"),
    ("Mic ligado", "Mic on"),
    ("Ligando…", "Turning on…"),
    ("Não abriu", "Failed"),
    ("Abrindo…", "Opening…"),
    ("Fechando…", "Closing…"),
    ("Gravar", "Record"),
    ("Gravando", "Recording"),
    ("{} · SEM SOM", "{} · NO AUDIO"),
    ("Parar e salvar", "Stop and save"),
    // modelo_da_janela.rs — os exemplos (o retrato de bancada) e as notas da barra
    ("{} (principal)", "{} (primary)"),
    ("Câmera", "Camera"),
    ("Tela ou câmera", "Screen or camera"),
    ("Ninguém anunciando. Use o endereço que aparece no outro aparelho.", "No one is announcing. Use the address shown on the other device."),
    ("Indo junto", "Included"),
    ("Um papel por vez. Pare de espelhar para usar os outros.", "One role at a time. Stop mirroring to use the others."),
    ("Um papel por vez. Pare de exibir para usar os outros.", "One role at a time. Stop receiving to use the others."),
    ("O teleprompter com a câmera está aberto: feche-o para espelhar daqui.", "The teleprompter with camera is open: close it to mirror from here."),
    ("O PIN não conferiu. Digite os seis dígitos que aparecem no outro aparelho.", "The PIN didn't match. Type the six digits shown on the other device."),
    ("O Windows recusou a saída de som padrão: vai sem som.", "Windows refused the default audio output: going without audio."),
    ("O microfone abre quando o outro aparelho conectar.", "The microphone opens when the other device connects."),
    ("O aparelho não entrou com o pareamento guardado: esqueça os pareamentos e use o PIN.", "The device couldn't join with the saved pairing: forget pairings and use the PIN."),
    ("Espelhando", "Mirroring"),
    ("Da câmera", "Camera"),
    ("Com o som deste computador, num aparelho só.", "With this computer's audio, on one device only."),
    ("Limite de {} aparelhos: para entrar mais um, outro precisa sair.", "Limit of {} devices: for one more to join, another must leave."),
    ("Exibindo", "Receiving"),
    // janela.rs
    ("se for a 1ª vez", "if it's the first time"),
    ("ex.: 192.168.0.12:7877", "e.g. 192.168.0.12:7877"),
    ("A procura na rede não subiu — digite o endereço.", "Network search didn't start — type the address."),
    ("Tela", "Screen"),
    ("Microfone desligado: a câmera vai sem som.", "Microphone off: the camera goes without audio."),
    ("sem rede", "no network"),
    ("Sem som", "No audio"),
    ("Abrindo a espera por mais um aparelho…", "Opening a spot for one more device…"),
    ("Sem som — só imagem.", "No audio — picture only."),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("a tela estendida", "the extended display"),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("Monitor novo", "New display"),
    // estilo.rs
    ("Ligado", "On"),
    ("Desligado", "Off"),
    ("Copiado", "Copied"),
    // regras_da_tela_estendida.rs
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("Tela estendida", "Extended display"),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("Um monitor novo para cada aparelho", "A new display for each device"),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("Precisa do driver SudoVDA", "Needs the SudoVDA driver"),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("Tela estendida, precisa do driver SudoVDA. Abre no navegador a página com as instruções de instalação", "Extended display, needs the SudoVDA driver. Opens the installation instructions page in the browser"),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("os monitores da vez anterior ainda estão saindo; espere alguns segundos", "the displays from last time are still being removed; wait a few seconds"),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("A tela estendida não está disponível: {}. Toque em Espelhar para tentar de novo.", "The extended display isn't available: {}. Click Mirror to try again."),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("nenhuma placa de vídeo de hardware foi encontrada", "no hardware graphics card was found"),
    #[cfg(any(test, feature = "tela-estendida-futura"))]
    ("nenhuma placa de vídeo deste computador tem um codificador H.264 de hardware", "no graphics card in this computer has a hardware H.264 encoder"),
    // sessoes.rs (os conselhos da tela estendida e de várias sessões)
    ("A captura do Windows não respondeu. Reiniciar o Windows costuma resolver.", "Windows capture didn't respond. Restarting Windows usually fixes it."),
    ("Não consegui abrir a espera por mais um aparelho: {}", "Couldn't open a spot for one more device: {}"),
    ("O outro aparelho", "The other device"),
    ("{} saiu.", "{} left."),
    ("A conexão com {} caiu.", "The connection to {} dropped."),
    ("Um aparelho tentou entrar com o PIN errado. O PIN mudou: passe os seis dígitos novos — cada PIN vale uma tentativa por conexão.", "A device tried to join with the wrong PIN. The PIN changed: share the six new digits — each PIN is good for one try per connection."),
    ("Um aparelho tentou entrar com o PIN errado. Clique em Espelhar de novo e passe os seis dígitos novos — cada PIN vale uma tentativa por conexão.", "A device tried to join with the wrong PIN. Click Mirror again and share the six new digits — each PIN is good for one try per connection."),
    ("O pareamento de mais um aparelho não fechou. Ou o PIN não conferiu, ou o outro aparelho tentou entrar com um pareamento que este computador não reconhece mais. O PIN mudou: digite no outro aparelho o PIN novo que aparece aqui.", "Pairing one more device didn't complete. Either the PIN didn't match, or the other device tried to join with a pairing this computer no longer recognizes. The PIN changed: enter on the other device the new PIN shown here."),
];
