//! A tabela de tradução: mensagens (ver `idioma.rs`). `(português, inglês)`, com os `{}` nas mesmas
//! posições de ordem; o português é o texto que está no código.

pub const TEXTOS: &[(&str, &str)] = &[
    // Inicialização sem console: o motivo também vai ao diário de diagnóstico.
    ("O Quall Monitor não conseguiu iniciar.", "Quall Monitor could not start."),
    ("O Quall Monitor encontrou uma falha inesperada.", "Quall Monitor encountered an unexpected error."),
    ("O diário de diagnóstico não pôde ser aberto. As falhas de inicialização serão mostradas nesta janela.", "The diagnostic log could not be opened. Startup errors will be shown in this window."),
    ("Licenças", "Licenses"),
    ("Abrir as licenças de terceiros", "Open third-party licenses"),
    ("As licenças de terceiros não puderam ser abertas. Reinstale o Quall Monitor para recuperar o arquivo de avisos.", "The third-party licenses could not be opened. Reinstall Quall Monitor to restore the notices file."),
    // descoberta.rs (o motivo da lista; a janela e o teleprompter o mostram com `tr`)
    ("Não consegui procurar na rede. Digite o endereço.", "Couldn't search the network. Enter the address."),
    // instancia.rs
    ("O Quall ainda está fechando a sessão anterior. Espere um instante e abra de novo.", "Quall is still closing the previous session. Wait a moment and open it again."),
    // emissor.rs
    ("Com o som do microfone.", "With microphone audio."),
    ("Microfone abrindo…", "Microphone opening…"),
    ("Microfone desligado: a câmera vai sem som (a track do microfone está na oferta, calada).", "Microphone off: the camera goes without audio (the microphone track is in the offer, muted)."),
    ("Não consegui preparar o PIN: {}", "Couldn't prepare the PIN: {}"),
    ("Este computador não deixou capturar o som da saída de áudio; a transmissão vai só com imagem.", "This computer didn't allow capturing the audio output; the stream goes with picture only."),
    ("Som de {}", "Audio from {}"),
    ("Microfone de {}", "Microphone on {}"),
    ("A câmera \"{}\" não está mais conectada.", "The camera \"{}\" is no longer connected."),
    ("O monitor \"{}\" não está mais conectado.", "The display \"{}\" is no longer connected."),
    ("Não consegui iniciar a captura: {}", "Couldn't start the capture: {}"),
    ("A track de som foi negociada, mas a captura não subiu: o outro aparelho vai receber imagem sem som.", "The audio track was negotiated, but the capture didn't start: the other device will get picture without audio."),
    ("câmera {}×{} · ", "camera {}×{} · "),
    (" · {} quadros de som", " · {} audio frames"),
    ("{}{} quadros · {} IDR · captura+encode {} ms{}", "{}{} frames · {} IDR · capture+encode {} ms{}"),
    ("Um aparelho tentou entrar com um pareamento que este computador não reconhece mais. Peça para ele digitar o PIN de novo; se continuar falhando, esqueça os pareamentos e comecem do zero.", "A device tried to join with a pairing this computer no longer recognizes. Ask it to enter the PIN again; if it keeps failing, forget the pairings and start over."),
    ("Ninguém entrou em cinco minutos. Clique em Espelhar de novo quando o outro aparelho estiver pronto.", "No one joined in five minutes. Click Mirror again when the other device is ready."),
    ("O pareamento não fechou. Ou o PIN não conferiu, ou o outro aparelho tentou entrar com um pareamento que este computador não reconhece mais. Nos dois casos a saída é a mesma: clique em Espelhar de novo e digite no outro aparelho o PIN novo que aparecer aqui.", "Pairing didn't complete. Either the PIN didn't match, or the other device tried to join with a pairing this computer no longer recognizes. Either way, the fix is the same: click Mirror again and enter on the other device the new PIN shown here."),
    ("Pareamentos esquecidos. Da próxima vez o PIN será pedido.", "Pairings forgotten. The PIN will be asked next time."),
    ("Nenhum monitor foi encontrado neste computador.", "No display was found on this computer."),
    ("Escolha o que transmitir.", "Choose what to stream."),
    ("Tela estendida (um monitor novo para cada aparelho)", "Extended display (a new display for each device)"),
    ("Não gravou: {}", "Didn't record: {}"),
    ("Ninguém entrou em {} minutos, e nada estava gravando: a câmera fechou. Clique em Espelhar de novo quando o outro aparelho estiver pronto.", "No one joined in {} minutes and nothing was recording: the camera closed. Click Mirror again when the other device is ready."),
    ("Fechando o arquivo da gravação…", "Closing the recording file…"),
    ("Fechando o arquivo…", "Closing the file…"),
    ("Gravando SEM SOM — {}", "Recording with NO AUDIO — {}"),
    ("Gravando SEM SOM — o microfone está abrindo", "Recording with NO AUDIO — the microphone is opening"),
    ("Gravando SEM SOM — ligue o microfone", "Recording with NO AUDIO — turn on the microphone"),
    ("Gravação salva ({} s) em {}", "Recording saved ({} s) to {}"),
    ("A gravação fechou com defeito ({}); o arquivo é recuperado na próxima vez", "The recording closed with a fault ({}); the file is recovered next time"),
    ("● GRAVANDO {}", "● RECORDING {}"),
    (" · sobram {} GB", " · {} GB left"),
    ("■ Parar a gravação ({})", "■ Stop recording ({})"),
    ("Gravar (abrindo…)", "Record (opening…)"),
    ("Abrindo o arquivo…", "Opening the file…"),
    ("● Gravar", "● Record"),
    ("● Gravar neste computador", "● Record on this computer"),
    ("● Gravar neste computador (sem som)", "● Record on this computer (no audio)"),
    // sessao_de_emissao.rs, varias.rs, monitores_virtuais.rs (o motivo que chega à tela; o detalhe técnico vai como veio)
    ("O monitor \"{}\" foi desconectado.", "The display \"{}\" was disconnected."),
    ("O outro aparelho saiu.", "The other device left."),
    ("A transmissão parou: {}.", "The stream stopped: {}."),
    (" · {} repetidos", " · {} repeated"),
    ("o monitor \"{}\" não está mais conectado", "the display \"{}\" is no longer connected"),
    ("O monitor \"{}\" mudou de tamanho.", "The display \"{}\" changed size."),
    ("a captura do monitor não abriu", "the display capture didn't open"),
    ("Tela estendida de {}", "Extended display for {}"),
    ("outro aparelho", "other device"),
    ("esperando a sessão anterior deste aparelho sair", "waiting for this device's previous session to end"),
    ("{} × {}, índice {}", "{} × {}, index {}"),
    ("{} · com o som", "{} · with audio"),
    ("Os monitores virtuais pararam (o fio que cuida deles caiu); o SudoVDA os tira em 2–3 s.", "The virtual displays stopped (the thread that manages them crashed); SudoVDA removes them in 2–3 s."),
    ("A tela deste computador mudou enquanto um monitor novo entrava: os monitores virtuais saíram para não mexer nela.", "This computer's display layout changed while a new display was being added: the virtual displays were removed so as not to disturb it."),
    ("o SudoVDA não põe o monitor novo em caminho disponível nenhum (targetAvailable=0 em todos por 3 s): é a assinatura do adaptador travado, §12.3. Reiniciar o Windows costuma resolver.", "SudoVDA isn't putting the new display on any available path (targetAvailable=0 on all for 3 s): that's the sign of a stuck adapter, §12.3. Restarting Windows usually fixes it."),
    ("o monitor não ficou pronto em {} s ({})", "the display wasn't ready in {} s ({})"),
    ("a tela do usuário mudou depois do pedido ({}); ela voltou à foto sem os monitores virtuais, e este não nasce", "the user's display layout changed after the request ({}); it was restored without the virtual displays, and this one isn't created"),
    ("o monitor deste aparelho ainda está com outra sessão", "this device's display is still held by another session"),
    ("o Windows pôs o monitor em {}x{}, e o pedido era {}x{}: a sessão não abre num tamanho que não é o da tela do aparelho", "Windows set the display to {}x{}, but {}x{} was requested: the session won't open at a size that isn't the device's screen"),
    ("outro Quall aberto neste computador já está usando a tela estendida (o vigia do SudoVDA é de todos): um de cada vez", "another Quall open on this computer is already using the extended display (the SudoVDA watchdog is shared): one at a time"),
    ("o driver SudoVDA não está instalado ou o adaptador dele está desligado", "the SudoVDA driver isn't installed or its adapter is disabled"),
    ("o driver SudoVDA não respondeu ({})", "the SudoVDA driver didn't respond ({})"),
    ("o driver SudoVDA não disse a versão (GET_PROTOCOL_VERSION: {})", "the SudoVDA driver didn't report its version (GET_PROTOCOL_VERSION: {})"),
    ("esta versão do driver SudoVDA (protocolo {}) não é a que o Quall conhece ({})", "this SudoVDA driver version (protocol {}) isn't the one Quall knows ({})"),
    ("outro programa está usando o SudoVDA agora, com um monitor ligado ({}); feche-o e tente de novo", "another program is using SudoVDA right now, with a display on ({}); close it and try again"),
    ("{} Toque em Parar e depois em Espelhar para abrir de novo.", "{} Tap Stop and then Mirror to open it again."),
];
