//! Strings unique to the Monitor public shell and startup.
pub const TEXTOS: &[(&str, &str)] = &[
    ("Quall Monitor — até 8 telas estendidas pela rede local", "Quall Monitor — up to 8 extended displays over the local network"),
    ("quall-monitor [OPÇÕES]", "quall-monitor [OPTIONS]"),
    ("{about}\n\nUso: {usage}\n\n{all-args}", "{about}\n\nUsage: {usage}\n\n{all-args}"),
    ("Arquivo do diário; o padrão pertence apenas ao Quall Monitor.", "Log file; the default belongs only to Quall Monitor."),
    ("Porta da sinalização; zero escolhe uma porta livre.", "Signaling port; zero selects an available port."),
    ("Taxa alvo do vídeo, de 1 a 60 quadros por segundo.", "Target video frame rate, from 1 to 60 frames per second."),
    ("Estender sem transmitir o som deste computador.", "Extend without sending this computer's audio."),
    ("Mostrar ajuda", "Show help"),
    ("Mostrar versão", "Show version"),
    ("Opções", "Options"),
    ("Quall Monitor não conseguiu iniciar.\n\n{}", "Quall Monitor couldn't start.\n\n{}"),
    ("As opções de inicialização não foram aceitas.\n\n{}", "The startup options weren't accepted.\n\n{}"),
    ("O diário do Quall Monitor não pôde ser aberto.", "The Quall Monitor log couldn't be opened."),
    ("Até 8 aparelhos, cada um com um monitor. No outro aparelho, escolha Exibir.", "Up to 8 devices, each with its own display. On the other device, choose Receive."),
    ("Pronto para estender", "Ready to extend"),
    ("Estendendo", "Extending"),
    ("Nome deste computador", "This computer's name"),
    ("Estendendo para", "Extending to"),
    ("Estendendo para 1 aparelho", "Extending to 1 device"),
    ("Estendendo para {} aparelhos", "Extending to {} devices"),
    ("O outro aparelho precisa já ter clicado em Estender: quem exibe só entra depois de quem transmite estar esperando.", "The other device must have clicked Extend: the receiver can join once the sender is waiting."),
    ("Pare de estender para exibir outra tela ou abrir os Ajustes.", "Stop extending to receive another display or open Settings."),
];
