//! A tabela de tradução: receptor (ver `idioma.rs`). `(português, inglês)`, com os `{}` nas mesmas
//! posições de ordem; o português é o texto que está no código.

pub const TEXTOS: &[(&str, &str)] = &[
    // receptor.rs — o título da janela de vídeo
    (" · {}x{} a {} fps", " · {}x{} at {} fps"),
    ("{} · {} quadros suspeitos na sessão", "{} · {} suspect frames this session"),
    ("{} · ⚠ {} quadros suspeitos agora · {} na sessão", "{} · ⚠ {} suspect frames now · {} this session"),
    (" · a placa de vídeo parou {}× e a imagem foi reaberta", " · the graphics card stopped {}× and the picture was reopened"),
    // receptor.rs — a linha do som
    ("som: {}", "audio: {}"),
    ("som: tocando, volume {} %", "audio: playing, volume {}%"),
    ("sem som: {}", "no audio: {}"),
    ("a track de som não disse o codec", "the audio track didn't say its codec"),
    ("a porta puxada não abriu: {}", "the audio port didn't open: {}"),
    ("o tocador não subiu: {}", "the player didn't start: {}"),
    ("a saída está sendo montada", "the output is being set up"),
    ("som: nada chegando do emissor (o som pode estar com outro receptor)", "audio: nothing arriving from the sender (the audio may be on another receiver)"),
    // som_puxado.rs (`por_que_calado`, traduzido na linha do som do receptor)
    ("mudo", "muted"),
    ("mudo: a câmera do Quall está em uso", "muted: the Quall camera is in use"),
    ("volume zero", "volume at zero"),
    // receptor.rs — os conselhos
    ("Não entendi \"{}\". Escreva o endereço como aparece no outro aparelho — por exemplo 192.168.1.41:7877. ({})", "Couldn't read \"{}\". Type the address as it shows on the other device — for example 192.168.1.41:7877. ({})"),
    ("Escolha um aparelho na lista, ou digite o endereço dele.", "Pick a device from the list, or type its address."),
    ("Esse PIN não tem a forma certa: {}", "That PIN isn't in the right format: {}"),
    ("{} conectou, mas não mandou nenhuma track de vídeo em 15 segundos.", "{} connected, but sent no video track in 15 seconds."),
    ("{} parou de transmitir.", "{} stopped streaming."),
    ("A conexão caiu.", "The connection dropped."),
    ("Você fechou a janela do vídeo.", "You closed the video window."),
    ("Não consegui abrir o vídeo: {}", "Couldn't open the video: {}"),
    ("A placa de vídeo deste computador parou {} vezes durante a transmissão. Tente de novo; se voltar a acontecer, atualize o driver de vídeo.", "This computer's graphics card stopped {} times during the stream. Try again; if it happens again, update the graphics driver."),
    ("{} quadros · {} ms da fila à tela", "{} frames · {} ms from queue to screen"),
    ("O outro aparelho não reconhece mais este pareamento e pediu para recomeçar. Digite aqui o PIN que está aparecendo na tela dele.", "The other device no longer recognizes this pairing and asked to start over. Type here the PIN showing on its screen."),
    ("O pareamento não fechou. Ou o PIN não conferiu, ou o outro aparelho não reconhece mais este pareamento — deste lado as duas causas chegam iguais. Nos dois casos a saída é a mesma: peça o PIN que está na tela do outro aparelho e digite-o aqui.", "Pairing didn't complete. Either the PIN didn't match, or the other device no longer recognizes this pairing — from this side both look the same. Either way, the fix is the same: get the PIN on the other device's screen and type it here."),
    ("O pareamento fechou, mas os dois aparelhos não acharam caminho um para o outro. Quase sempre é a rede: Wi-Fi de hóspede, isolamento entre aparelhos ou redes diferentes. Ponha os dois na mesma rede e tente de novo.", "Pairing worked, but the two devices couldn't reach each other. It's almost always the network: guest Wi-Fi, client isolation or different networks. Put both on the same network and try again."),
    ("O outro aparelho não respondeu. Confira se ele já clicou em Espelhar — quem exibe só entra depois de quem transmite estar esperando.", "The other device didn't answer. Check that it already clicked Mirror — the receiver can only join once the sender is waiting."),
    ("Não consegui falar com esse endereço. Confira o número e a porta, e se o outro aparelho está esperando.", "Couldn't reach that address. Check the number and port, and that the other device is waiting."),
    ("Pareamentos esquecidos. Digite o PIN que está na tela do outro aparelho.", "Pairings forgotten. Type the PIN showing on the other device's screen."),
    // placa.rs (a placa de espera da câmera virtual), regras_r5.rs, regras_da_gravacao.rs
    ("Procurando aparelhos…", "Looking for devices…"),
    ("Conectando…", "Connecting…"),
    ("Conectado — esperando a imagem", "Connected — waiting for the picture"),
    ("Nenhum aparelho conectado", "No device connected"),
    ("O aparelho saiu", "The device left"),
    ("Quall está procurando na rede local.", "Quall is looking on the local network."),
    ("Pareando com o aparelho escolhido.", "Pairing with the chosen device."),
    ("O primeiro quadro chega assim que o emissor mandar uma imagem completa.", "The first frame arrives as soon as the sender sends a full picture."),
    ("No celular: abra o Quall, escolha o que transmitir e toque em Espelhar.", "On your phone: open Quall, choose what to stream and tap Mirror."),
    ("Para voltar, toque em Espelhar de novo no aparelho.", "To come back, tap Mirror again on the device."),
    ("O Windows não deixa este app usar o microfone. Ligue em Configurações → Privacidade e segurança → Microfone: \"Acesso ao microfone\" e \"Permitir que aplicativos da área de trabalho acessem o microfone\".", "Windows isn't letting this app use the microphone. Turn on Settings → Privacy & security → Microphone: \"Microphone access\" and \"Let desktop apps access your microphone\"."),
    ("O microfone não abriu.", "The microphone didn't open."),
    ("O microfone não abriu: {}", "The microphone didn't open: {}"),
    ("sem espaço: sobram {} MB (gravar pede {} MB livres)", "not enough space: {} MB left (recording needs {} MB free)"),
    ("SEM SOM", "NO AUDIO"),
    ("não deu para gravar", "couldn't record"),
    // regras_da_camera.rs (as frases da câmera que vão à tela)
    ("Câmera parada há {} s — esperando ela voltar.", "Camera paused for {} s — waiting for it to come back."),
    ("A abertura da câmera foi interrompida pelo Parar.", "Opening the camera was interrupted by Stop."),
    ("A câmera não está mais conectada.", "The camera is no longer connected."),
    ("O Windows negou o acesso à câmera: veja Privacidade e segurança > Câmera.", "Windows denied access to the camera: see Privacy & security > Camera."),
    ("A câmera está em uso por outro app.", "The camera is in use by another app."),
    ("A câmera não mandou nenhum quadro.", "The camera sent no frames."),
    ("A câmera não abriu.", "The camera didn't open."),
    ("A câmera \"{}\" foi desconectada.", "The camera \"{}\" was disconnected."),
    ("O Windows negou o acesso à câmera \"{}\": veja Privacidade e segurança > Câmera.", "Windows denied access to the camera \"{}\": see Privacy & security > Camera."),
    ("Outro app tomou a câmera \"{}\".", "Another app took the camera \"{}\"."),
    ("A câmera \"{}\" mudou de formato: comece a transmissão de novo.", "The camera \"{}\" changed format: start the stream again."),
    ("A câmera \"{}\" parou.", "The camera \"{}\" stopped."),
    // microfone.rs, dono_da_captura.rs, catalogo_de_cameras.rs, fontes.rs
    ("O microfone ainda está fechando; tente de novo em um instante.", "The microphone is still closing; try again in a moment."),
    ("O microfone não abriu: a thread não subiu ({})", "The microphone didn't open: its thread didn't start ({})"),
    ("O microfone foi desconectado (ou trocado nas configurações de som).", "The microphone was disconnected (or changed in the sound settings)."),
    ("O microfone parou: {}", "The microphone stopped: {}"),
    ("O teleprompter com câmera está aberto e transmite a câmera deste computador. Feche aquela tela para espelhar daqui.", "The teleprompter with camera is open and streaming this computer's camera. Close that screen to mirror from here."),
    ("A janela principal está transmitindo (ou esperando para transmitir). Pare lá para abrir o texto com a câmera.", "The main window is streaming (or waiting to stream). Stop it there to open Text with camera."),
    ("a thread da câmera não subiu: {}", "the camera thread didn't start: {}"),
    ("nenhuma placa ativou um H.264 para a câmera ({})", "no graphics card started an H.264 encoder for the camera ({})"),
    ("\"{}\" não está mais disponível. Escolha outra fonte.", "\"{}\" is no longer available. Choose another source."),
    ("{} de {}", "{} on {}"),
    ("Câmera: {}", "Camera: {}"),
    (" (principal)", " (main)"),
    // gravador_local.rs (o motivo que chega à tela; o detalhe técnico vai como veio)
    ("a pasta Vídeos não foi achada: {}", "the Videos folder wasn't found: {}"),
    ("a pasta Vídeos veio vazia", "the Videos folder came back empty"),
    ("a pasta {} não foi criada: {}", "the folder {} couldn't be created: {}"),
    ("a imagem da câmera é pequena demais para gravar ({}x{})", "the camera picture is too small to record ({}x{})"),
    ("a câmera não está aberta", "the camera isn't open"),
    ("a câmera não está entregando imagem", "the camera isn't delivering a picture"),
    ("a pasta Vídeos não foi achada", "the Videos folder wasn't found"),
    ("o arquivo não abriu: {}", "the file didn't open: {}"),
    ("a gravação ficou sem entrada", "the recording lost its input"),
    ("a câmera não entregou imagem ao arquivo em {} s", "the camera didn't deliver a picture to the file in {} s"),
    ("o arquivo parou de receber imagem (o codificador não devolve as texturas)", "the file stopped receiving pictures (the encoder isn't returning the textures)"),
];
