//! A tabela de tradução: teleprompter (ver `idioma.rs`). `(português, inglês)`, com os `{}` nas mesmas
//! posições de ordem; o português é o texto que está no código.
//!
//! O inglês das frases que o iOS também tem é o mesmo do iOS (`Teleprompter.strings` e
//! `ComCamera.strings`): a pergunta do texto, os roteiros guardados, a contagem de palavras, o modo
//! "Segurar para rolar", Rolar/Pausar/Espelho, e "Controle" → "Remote".
//!
//! Frases do teleprompter que já estão em outras tabelas e não se repetem aqui: "● Gravar",
//! "Gravar (abrindo…)", "Fechando o arquivo…", "● GRAVANDO {}", "Não gravou: {}", "Câmera: {}",
//! " · {} quadros de som", "■ Parar a gravação ({})" e "Ajustes da câmera".

pub const TEXTOS: &[(&str, &str)] = &[
    // regras.rs — o conselho de conexão
    ("Cinco tentativas seguidas com o PIN errado: a espera parou, para ninguém ficar adivinhando o PIN. Clique em Esperar de novo.", "Five wrong PINs in a row: waiting stopped, so no one can keep guessing the PIN. Click Wait again."),
    ("Um aparelho tentou entrar com o PIN errado. O PIN mudou: passe os seis dígitos novos.", "A device tried to connect with the wrong PIN. The PIN changed: share the six new digits."),
    ("Um aparelho tentou entrar com um pareamento que este computador não reconhece mais: ele precisa digitar o PIN.", "A device tried to connect with a pairing this computer no longer recognizes: it needs to enter the PIN."),
    ("Um aparelho que não é controle do Quall, ou de outra versão, tentou entrar e foi recusado.", "A device that isn't a Quall remote, or runs another version, tried to connect and was refused."),
    ("A porta {} falhou ({}). Tentando de novo.", "Port {} failed ({}). Trying again."),
    ("A espera parou: {}", "Waiting stopped: {}"),
    ("PIN errado. Confira os seis dígitos na tela do prompter e conecte de novo — o PIN do prompter muda depois de um erro.", "Wrong PIN. Check the six digits on the prompter's screen and connect again — the prompter's PIN changes after a mistake."),
    ("O prompter não reconhece mais este computador. Digite o PIN que a tela dele mostra.", "The prompter no longer recognizes this computer. Enter the PIN shown on its screen."),
    ("O pareamento não fechou. Confira o PIN na tela do prompter e tente de novo.", "Pairing didn't complete. Check the PIN on the prompter's screen and try again."),
    ("Esse aparelho não aceitou este computador como controle: {}", "That device didn't accept this computer as a remote: {}"),
    ("O prompter já tem outro controle conectado.", "The prompter already has another remote connected."),
    ("O prompter ainda está com a sessão anterior — tentando de novo (ele percebe a queda em até 5 s).", "The prompter is still on the previous session — trying again (it notices the drop within 5 s)."),
    ("Conexão perdida — tentando de novo. Os comandos vão quando a conexão voltar.", "Connection lost — trying again. Commands go through when the connection is back."),
    ("Os dois aparelhos não acharam caminho um até o outro. Confira se estão na mesma rede.", "The two devices couldn't find a path to each other. Check that they're on the same network."),
    ("Ninguém atendeu neste endereço. Confira se o prompter está aberto e se o endereço e a porta estão certos.", "No one answered at this address. Check that the prompter is open and that the address and port are correct."),
    ("Não deu para conectar: {}", "Couldn't connect: {}"),
    // regras.rs — a tela cheia e o "Segurar para rolar"
    ("Sair da tela cheia", "Exit full screen"),
    ("Tela cheia", "Full screen"),
    ("Rolar para cima", "Scroll up"),
    ("Rolar para baixo", "Scroll down"),
    ("volta o texto", "moves the text back"),
    ("avança o texto", "moves the text forward"),
    ("O texto parou. Solte e aperte de novo.", "The text stopped. Release and press again."),
    ("O texto chegou ao fim.", "The text reached the end."),
    ("Esperando o prompter responder…", "Waiting for the prompter to respond…"),
    ("O prompter não responde há mais de 2,5 s. Os botões voltam quando ele responder.", "The prompter hasn't responded for over 2.5 s. The buttons come back when it does."),
    ("Atualize o app do prompter para usar este modo", "Update the app on the prompter to use this mode"),
    // regras.rs — a pergunta do texto e os roteiros guardados (o inglês do iOS)
    ("No prompter", "On the prompter"),
    ("Neste aparelho", "On this device"),
    ("Usar o do prompter", "Use the prompter's"),
    ("Mandar o meu", "Send mine"),
    ("O roteiro que sair fica em Roteiros guardados.", "The script that's replaced stays in Saved scripts."),
    ("Conferindo o roteiro do prompter…", "Checking the prompter's script…"),
    ("O prompter saiu. A pergunta volta quando ele voltar.", "The prompter left. The question comes back when it returns."),
    ("O roteiro do prompter mudou. Confira de novo.", "The prompter's script changed. Check again."),
    ("Roteiros guardados", "Saved scripts"),
    ("Nenhum roteiro guardado.", "No saved scripts."),
    ("Usar este roteiro? Ele substitui o roteiro atual, também no prompter conectado.", "Use this script? It replaces the current script, also on the connected prompter."),
    ("Apagar este roteiro guardado?", "Delete this saved script?"),
    ("O prompter {} tem outro roteiro.", "The prompter {} has a different script."),
    ("1 palavra", "1 word"),
    ("{} palavras", "{} words"),
    ("Do prompter {}", "From the prompter {}"),
    ("Deste aparelho, antes de {}", "From this device, before {}"),
    // regras.rs — o roteiro e o "Abrir arquivo .txt…"
    ("{} KB de {} KB", "{} KB of {} KB"),
    ("O roteiro tem {} bytes; o máximo é {} (cerca de 20 mil palavras).", "The script is {} bytes; the maximum is {} (about 20,000 words)."),
    ("O arquivo não está em UTF-8 nem em UTF-16 com BOM; salve-o como UTF-8 e abra de novo.", "The file isn't UTF-8 or UTF-16 with BOM; save it as UTF-8 and open it again."),
    ("Não consegui ler o arquivo: {}", "Couldn't read the file: {}"),
    ("Sem roteiro.", "No script."),
    // sessao.rs
    ("Nenhuma porta de {} a {} abriu neste computador ({}).", "No port from {} to {} opened on this computer ({})."),
    ("Não entendi o endereço {}: {}", "Couldn't read the address {}: {}"),
    ("O PIN tem de ter seis dígitos ({}).", "The PIN must have six digits ({})."),
    // camera.rs (o vídeo da tela R5)
    ("Não consegui preparar o PIN do vídeo: {}", "Couldn't prepare the video PIN: {}"),
    ("O vídeo desistiu depois de {} tentativas seguidas que não firmaram.", "The video gave up after {} attempts in a row that didn't hold."),
    ("Um aparelho tentou entrar com um pareamento que este computador não reconhece mais: peça para ele digitar o PIN novo, ou esqueça os pareamentos.", "A device tried to connect with a pairing this computer no longer recognizes: ask it to enter the new PIN, or forget the pairings."),
    ("O pareamento não fechou (o PIN não conferiu, ou um pareamento esquecido): o PIN mudou; digite o novo no outro aparelho.", "Pairing didn't complete (the PIN didn't match, or a pairing was forgotten): the PIN changed; enter the new one on the other device."),
    ("A conexão não fechou: {}", "The connection didn't complete: {}"),
    ("A transmissão não começou: {}", "The stream didn't start: {}"),
    ("câmera {}×{} · {} quadros · {} IDR{}", "camera {}×{} · {} frames · {} IDR{}"),
    ("Quem recebia saiu; esperando de novo.", "The receiver left; waiting again."),
    ("{} Esperando de novo.", "{} Waiting again."),
    ("O vídeo foi encerrado.", "The video ended."),
    // divisao.rs
    ("Texto: em cima", "Text: top"),
    ("Texto: embaixo", "Text: bottom"),
    ("Texto: à esquerda", "Text: left"),
    ("Texto: à direita", "Text: right"),
    // tela.rs — os comandos
    ("Editar", "Edit"),
    ("Rolar", "Scroll"),
    ("Pausar", "Pause"),
    ("Vel −", "Speed −"),
    ("Vel +", "Speed +"),
    ("A −", "A −"),
    ("A +", "A +"),
    ("Margem −", "Margin −"),
    ("Margem +", "Margin +"),
    ("Linha ↑", "Line ↑"),
    ("Linha ↓", "Line ↓"),
    ("Espelho", "Mirror"),
    ("Início", "Start"),
    // tela.rs — os botões
    ("Mostrar o texto neste computador", "Show the text on this computer"),
    ("Controlar um teleprompter", "Control a teleprompter"),
    ("Mostrar o texto com a câmera deste computador", "Show the text with this computer's camera"),
    ("Conectar", "Connect"),
    ("Desconectar", "Disconnect"),
    ("Voltar", "Back"),
    ("Fonte automática", "Automatic font size"),
    ("Segurar para rolar", "Hold to scroll"),
    ("Sair do modo", "Exit mode"),
    ("Inverter botões", "Swap buttons"),
    ("Fechar", "Close"),
    ("Cancelar", "Cancel"),
    ("Voltar à lista", "Back to list"),
    ("Esperar de novo", "Wait again"),
    ("Confirmar", "Confirm"),
    ("Usar o texto novo", "Use the new text"),
    ("Manter o meu", "Keep Mine"),
    ("Abrir arquivo .txt…", "Open .txt file…"),
    ("Esconder a câmera", "Hide the camera"),
    ("Prévia como espelho", "Mirror the preview"),
    ("Editar ou colar o roteiro", "Edit or paste the script"),
    ("Ver", "View"),
    ("Usar este", "Use this one"),
    ("Apagar", "Delete"),
    ("Usar", "Use"),
    // tela.rs — o diálogo do "Abrir arquivo .txt…" e o editor
    ("Texto (*.txt)", "Text (*.txt)"),
    ("Todos os arquivos", "All files"),
    ("Abrir roteiro", "Open script"),
    ("O seu rascunho foi para a área de transferência.", "Your draft went to the clipboard."),
    ("Não consegui pôr o seu rascunho na área de transferência.", "Couldn't put your draft on the clipboard."),
    ("Não consegui abrir a janela de escolher arquivo.", "Couldn't open the file picker."),
    ("Roteiro", "Script"),
    ("O texto só vai para o outro aparelho ao confirmar.", "The text only goes to the other device when you confirm."),
    (" · o texto foi atualizado pelo outro aparelho", " · the text was updated by the other device"),
    ("O texto mudou no outro aparelho enquanto você editava. Usar o texto novo, ou manter o seu (ao confirmar, o seu vale nos dois).", "The text changed on the other device while you were editing. Use the new text, or keep yours (when you confirm, yours wins on both)."),
    // tela.rs — os títulos
    ("Quall — Teleprompter", "Quall — Teleprompter"),
    ("Quall — Teleprompter com câmera", "Quall — Teleprompter with camera"),
    ("Quall — Teleprompter: mostrando o texto", "Quall — Teleprompter: showing the text"),
    ("Quall — Teleprompter: controle", "Quall — Teleprompter: remote"),
    // tela.rs — a escolha e o formulário do controle
    ("Teleprompter", "Teleprompter"),
    ("Este computador aparece na rede como {}", "This computer shows up on the network as {}"),
    ("Todo aparelho faz os dois papéis: este computador mostra o texto (atrás do vidro), ou controla o texto que outro aparelho mostra. O texto se edita dos dois lados.", "Every device can play both roles: this computer shows the text (behind the glass), or controls the text another device shows. The text can be edited on both sides."),
    ("Não consegui criar o teleprompter: {}", "Couldn't create the teleprompter: {}"),
    ("Digite o endereço que a tela do prompter mostra (por exemplo 192.168.15.20).", "Enter the address shown on the prompter's screen (for example 192.168.15.20)."),
    ("NA REDE", "ON THE NETWORK"),
    ("Procurando prompters… (no outro aparelho: Quall → Teleprompter → Mostrar o texto)", "Looking for prompters… (on the other device: Quall → Teleprompter → Show the text)"),
    ("{} prompter(s) na rede — clique duas vezes para conectar", "{} prompter(s) on the network — double-click to connect"),
    ("NÃO ACHOU? DIGITE O ENDEREÇO QUE O PROMPTER MOSTRA", "NOT LISTED? ENTER THE ADDRESS THE PROMPTER SHOWS"),
    ("Deixe vazio se este computador e o prompter já se parearam antes.", "Leave empty if this computer and the prompter have paired before."),
    ("ROTEIRO", "SCRIPT"),
    ("vai ao prompter ao conectar; se ele tiver outro, a tela pergunta qual usar.", "goes to the prompter when you connect; if it has another one, you'll be asked which to use."),
    ("o texto vai ao prompter ao confirmar no editor.", "the text goes to the prompter when you confirm in the editor."),
    // tela.rs — o controle conectado
    ("Controlando {}", "Controlling {}"),
    ("Conexão perdida — tentando de novo ({})", "Connection lost — trying again ({})"),
    ("Desconectando…", "Disconnecting…"),
    ("Conectando em {}…", "Connecting to {}…"),
    ("O prompter não responde. Os comandos vão quando a conexão voltar.", "The prompter isn't responding. Commands go through when the connection is back."),
    ("O comando não chegou ao prompter (sem confirmação há mais de 1,5 s).", "The command didn't reach the prompter (no confirmation for over 1.5 s)."),
    ("O prompter fala outra versão do teleprompter: atualize o app nos dois aparelhos.", "The prompter uses a different teleprompter version: update the app on both devices."),
    ("O relógio de um dos dois aparelhos está mais de um dia errado: edições foram recusadas.", "One of the two devices' clocks is off by more than a day: edits were rejected."),
    ("O roteiro não passou para o prompter (ele o recusou 20 vezes).", "The script didn't reach the prompter (it refused it 20 times)."),
    ("Tudo confirmado pelo prompter.", "Everything confirmed by the prompter."),
    ("Posição no prompter: {}{}", "Position on the prompter: {}{}"),
    (" — rolando", " — scrolling"),
    (" — parado", " — stopped"),
    ("sim", "yes"),
    ("não", "no"),
    ("Velocidade {} linha(s)/s  ·  Fonte {}  ·  Margem {}  ·  Linha de leitura {}  ·  Espelho: {}", "Speed {} line(s)/s  ·  Font {}  ·  Margin {}  ·  Reading line {}  ·  Mirror: {}"),
    ("Roteiro: resumo {}", "Script: digest {}"),
    ("Teclado: espaço rola/pausa · ↑↓ velocidade (Shift = 1) · ←→ pular 5 % (Shift = 10 %) · Home começo · M espelho · + − fonte · [ ] margem · PgUp PgDn linha · E editar", "Keyboard: space scroll/pause · ↑↓ speed (Shift = 1) · ←→ skip 5% (Shift = 10%) · Home start · M mirror · + − font · [ ] margin · PgUp PgDn line · E edit"),
    // tela.rs — o modo "Segurar para rolar" no controle
    ("Sem conexão com o prompter — tentando de novo. Os botões voltam com ele.", "No connection to the prompter — trying again. The buttons come back with it."),
    ("{} não responde", "{} isn't responding"),
    ("Saindo…", "Leaving…"),
    ("Conexão perdida", "Connection lost"),
    ("  ·  botões invertidos", "  ·  buttons swapped"),
    ("{}  ·  Velocidade {} linhas/s  ·  ↑ e ↓ também seguram{}", "{}  ·  Speed {} lines/s  ·  ↑ and ↓ also hold{}"),
    // tela.rs — o prompter
    ("Sem roteiro. Clique em Editar, ou mande o texto pelo controle.", "No script. Click Edit, or send the text from the remote."),
    ("Linha de leitura {}", "Reading line {}"),
    ("Enquadramento {}", "Framing {}"),
    ("sem rede", "no network"),
    ("A espera parou. {}", "Waiting stopped. {}"),
    ("   ·   a porta {} estava ocupada: use a {}", "   ·   port {} was busy: use {}"),
    ("Anunciando na rede. No outro aparelho: Quall → Teleprompter → Controlar.", "Announcing on the network. On the other device: Quall → Teleprompter → Remote."),
    ("Sem anúncio na rede: digite o endereço no controle.", "Not announced on the network: enter the address on the remote."),
    ("CONTROLE SUMIDO — o texto continua como estava. Esperando o controle voltar.", "REMOTE GONE — the text stays as it was. Waiting for the remote to come back."),
    ("Controlado por {}", "Controlled by {}"),
    ("Esperando o controle", "Waiting for the remote"),
    (" (automática)", " (automatic)"),
    (" · espelho", " · mirror"),
    ("{} linha/s · fonte {}{} · margem {} · linha {}{}", "{} lines/s · font {}{} · margin {} · line {}{}"),
    (" · o controle fala outra versão: atualize o app", " · the remote uses another version: update the app"),
    (" · a última edição daqui não foi confirmada", " · the last edit here wasn't confirmed"),
    ("Fonte automática desligada: {}", "Automatic font size off: {}"),
    ("a fonte foi mudada aqui", "the font size was changed here"),
    ("o controle mudou a fonte", "the remote changed the font size"),
    // tela_r5.rs — o texto com a câmera
    ("Outro Quall já mostra o teleprompter com a câmera neste computador.", "Another Quall is already showing the teleprompter with the camera on this computer."),
    ("nenhuma câmera", "no camera"),
    ("Microfone: ligado", "Microphone: on"),
    ("Microfone: abrindo…", "Microphone: opening…"),
    ("Microfone: negado", "Microphone: denied"),
    ("Microfone: falhou", "Microphone: failed"),
    ("Microfone: desligado", "Microphone: off"),
    ("■ Parar {}", "■ Stop {}"),
    ("● Gravar (sem som)", "● Record (no audio)"),
    ("Abrindo a câmera \"{}\"…", "Opening the camera \"{}\"…"),
    ("A câmera não abriu: {}", "The camera didn't open: {}"),
    ("{} Escolha a câmera de novo para reabrir.", "{} Choose the camera again to reopen it."),
    ("A câmera está fechada.", "The camera is closed."),
    ("Câmera escondida — a transmissão e a gravação seguem.", "Camera hidden — streaming and recording continue."),
    ("A prévia não desenha nesta sessão ({}). A câmera, a transmissão e a gravação seguem.", "The preview can't draw in this session ({}). The camera, streaming and recording continue."),
    ("Texto: a espera parou. {}", "Text: waiting stopped. {}"),
    ("CONTROLE SUMIDO — o texto segue", "REMOTE GONE — the text continues"),
    ("controlado por {}", "controlled by {}"),
    ("esperando o controle", "waiting for the remote"),
    ("Texto: PIN {} · {} · {}", "Text: PIN {} · {} · {}"),
    ("Vídeo: encerrado", "Video: ended"),
    ("Vídeo: esperando a câmera abrir", "Video: waiting for the camera to open"),
    ("Vídeo: PIN {} · {} · esperando o receptor", "Video: PIN {} · {} · waiting for a receiver"),
    ("Vídeo: transmitindo para {} · {}", "Video: streaming to {} · {}"),
    ("Vídeo: parado — {}", "Video: stopped — {}"),
    (" · sobram {}", " · {} left"),
    (" · Gravando SEM SOM — ligue o microfone", " · Recording with NO AUDIO — turn on the microphone"),
    ("O controle fala outra versão: atualize o app", "The remote uses another version: update the app"),
    (" · espelho do texto", " · text mirrored"),
    ("como espelho", "mirrored"),
    ("sem espelho", "not mirrored"),
    ("{} linha/s · fonte {} · margem {} · linha {}{} · prévia {}", "{} lines/s · font {} · margin {} · line {}{} · preview {}"),
    ("Pare a gravação para trocar de câmera.", "Stop recording to switch cameras."),
    ("o prompter não está na tela que grava", "the prompter isn't on the recording screen"),
    ("Gravação salva ({}) em {}", "Recording saved ({}) to {}"),
    ("A gravação fechou com defeito ({}); o arquivo é recuperado na próxima abertura", "The recording closed with a fault ({}); the file is recovered the next time it opens"),
    ("O controle pediu para gravar, e não deu: {}", "The remote asked to record, and it couldn't: {}"),
    // tela_r5.rs — o gravar no prompter, na tela do controle
    ("Gravando… (esperando o prompter)", "Recording… (waiting for the prompter)"),
    ("Parando… (esperando o prompter)", "Stopping… (waiting for the prompter)"),
    ("● Gravar no prompter", "● Record on the prompter"),
    ("● O prompter está gravando há {}", "● The prompter has been recording for {}"),
    ("O prompter recusou gravar: {}", "The prompter refused to record: {}"),
    ("O prompter recusou parar: {}", "The prompter refused to stop: {}"),
];
